In [190]:
url = "https://bloqueioltau.site/Sublime_Sublime_1084356737/Risos_Mae_560734658/#&token=1810416138"

# Seperating different components

In [191]:
url = url.split("//")[1]

In [192]:
url

'bloqueioltau.site/Sublime_Sublime_1084356737/Risos_Mae_560734658/#&token=1810416138'

In [193]:
split_url = url.split("/")

In [194]:
split_url

['bloqueioltau.site',
 'Sublime_Sublime_1084356737',
 'Risos_Mae_560734658',
 '#&token=1810416138']

In [195]:
domain = split_url[0]

In [196]:
domain

'bloqueioltau.site'

In [197]:
directory = split_url[1]

In [198]:
directory

'Sublime_Sublime_1084356737'

In [199]:
file = split_url[2]

In [200]:
file

'Risos_Mae_560734658'

In [201]:
parameters = split_url[3]

## directory_length = Number of directory characters

In [202]:
directory

'Sublime_Sublime_1084356737'

In [203]:
numeric_directory_chars = 0
for char in directory:
    
    try:
        char = int(char)
        numeric_directory_chars+=1
    except:
        continue

# time_domain_activation in days : How many days have passed from when this domain was created

In [204]:
import datetime

In [205]:
import whois

In [206]:
def get_time_domain_activation(domain):
    try:
        
        res = whois.whois(domain)
        day_created = res['creation_date'][0]
        days= (datetime.datetime.now()-day_created).days
        return days
    except:
        return -1

In [207]:
r = get_time_domain_activation(url)

Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


In [208]:
len(file)

19

# length_url

In [209]:
url

'bloqueioltau.site/Sublime_Sublime_1084356737/Risos_Mae_560734658/#&token=1810416138'

In [210]:
len(url)

83

# file_length

In [211]:
file_length = len(file)

In [212]:
file_length 

19

# qty_slash_url

In [213]:
url

'bloqueioltau.site/Sublime_Sublime_1084356737/Risos_Mae_560734658/#&token=1810416138'

In [214]:
url.count("/")

3

# qty_plus_directory

In [215]:
directory

'Sublime_Sublime_1084356737'

In [216]:
qty_plus_directory = directory.count("+")

In [217]:
qty_plus_directory

0

# domain_length

In [218]:
domain

'bloqueioltau.site'

In [219]:
len(domain)

17

# qty_vowels_domain

In [220]:
qty_vowels_domain = 0
for i in domain:
    if i in {"a","e","i","o","u"}:
        qty_vowels_domain+=1

In [221]:
qty_vowels_domain

9

# qty_asterisk_directory

In [222]:
qty_asterisk_directory = directory.count("*")

In [223]:
qty_asterisk_directory

0

In [224]:
directory

'Sublime_Sublime_1084356737'

# qty_hyphen_directory

In [225]:
qty_hyphen_directory = directory.count("-")

In [226]:
qty_hyphen_directory

0

In [227]:
directory

'Sublime_Sublime_1084356737'

# qty_dot_domain

In [228]:
qty_dot_domain = domain.count(".")

In [229]:
qty_dot_domain

1

# qty_underline_directory

In [230]:
qty_underline_directory = directory.count("_")

In [231]:
qty_underline_directory

2

In [232]:
directory

'Sublime_Sublime_1084356737'

# qty_percent_directory

In [233]:
qty_percent_directory = directory.count("%")

In [234]:
qty_percent_directory

0

# qty_dot_url

In [235]:
qty_dot_url = url.count(".")

In [236]:
qty_dot_url

1

# qty_hyphen_url

In [237]:
qty_hyphen_url = url.count("-")

In [238]:
qty_hyphen_url

0

# qty_hyphen_file

In [239]:
qty_hyphen_file = file.count("-")

In [240]:
qty_hyphen_file

0

# qty_hyphen_domain

In [241]:
qty_hyphen_domain = domain.count("-")

In [242]:
qty_hyphen_domain

0

# params_length

In [243]:
params_length = len(parameters)

In [244]:
params_length

18

# qty_underline_url

In [245]:
qty_underline_url = url.count("_")

In [246]:
qty_underline_url

4

# qty_tld_url

In [247]:
top_level_domain = domain.split(".")[-1]

In [248]:
top_level_domain

'site'

In [249]:
qty_tld_url = len(top_level_domain)

In [250]:
qty_tld_url

4

# qty_plus_params

In [251]:
qty_plus_params = parameters.count("+")

In [252]:
qty_plus_params

0

# qty_percent_url

In [253]:
qty_percent_url = url.count("%")

In [254]:
qty_percent_url

0

# qty_equal_params

In [255]:
qty_equal_params = parameters.count("=")

In [256]:
qty_equal_params

1

# qty_dot_params

In [257]:
qty_dot_params = parameters.count(".")

In [258]:
qty_dot_params

0

# qty_underline_params

In [259]:
qty_underline_params = parameters.count("_")

In [260]:
qty_underline_params

0

# Final Class

In [261]:
import os

In [262]:
os.chdir("..")

In [263]:
from phishing_domain_detection.util import read_yaml_file

In [264]:
from phishing_domain_detection.constants import *

In [265]:
config  = read_yaml_file(CONFIG_FILE_PATH)

In [266]:
features = config[DATA_INGESTION_CONFIG_KEY][DATA_INGESTION_TOP_FEATURES_KEY]

In [267]:
features.pop()

'phishing'

In [268]:
from typing import List
import pandas as pd

In [269]:
import pandas as pd
import numpy as np
import datetime 

class FeatureExtractor:
    def __init__(self, columns):
       self.columns = columns
    
    @staticmethod
    def __extract_domain(url):
        try:
            return url.split("//")[1].split("/")[0]
        except Exception as e:
            return ""
    
    @staticmethod
    def __extract_directory(url):
        try:
            return url.split("//")[1].split("/")[1]
        except Exception as e:
            return ""
        
    @staticmethod
    def __extract_file(url):
        try:
            return url.split("//")[1].split("/")[2]
        except Exception as e:
            return ""
    
    @staticmethod
    def __extract_parameters(url):
        try:
            return url.split("//")[1].split("/")[3]
        except Exception as e:
            return ""
    
    @staticmethod
    def __extract_directory_length(directory):
        if directory == "":
            return -1
        return len(directory)
    
    @staticmethod
    def __extract_time_domain_activation(url):
        try:
            res = whois.whois(url)
            day_created = res['creation_date'][0]
            days= (datetime.datetime.now()-day_created).days
            return days
        except:
            return -1
    
    
    @staticmethod
    def __extract_length_url(url):
        return len(url)
    
    @staticmethod
    def __extract_file_length(file):
        
        if file == "":
            return -1
        
        return len(file)
    
    @staticmethod
    def __extract_qty_slash_url(url):
        return url.count("/")
    
    @staticmethod
    def __extract_qty_plus_directory(directory):
        return directory.count("+")
    
    @staticmethod
    def __extract_qty_vowels_domain(domain):
        qty_vowels_domain = 0
        for i in domain:
            if i in {"a","e","i","o","u"}:
                qty_vowels_domain+=1
        
        return qty_vowels_domain
    
    @staticmethod
    def __extract_qty_asterik_directory(directory):
        if directory == "":
            return -1
        
        return directory.count("*")
    
    @staticmethod
    def __extract_qty_hyphen_directory(directory):
        if directory == "":
            return  -1
        return directory.count("-")
    
    @staticmethod
    def __extract_qty_underline_directory(directory):
        if directory == "":
            return -1
        
        return directory.count("_")
    
    
    @staticmethod
    def __extract_qty_percent_directory(directory):
        if directory == "":
            return -1
        return directory.count("%")
    
    
    @staticmethod
    def __extract_qty_hyphen_file(file):
        if file == "":  
            return -1
        return file.count("-")
    
    @staticmethod
    def __extract_params_length(parameters):
        if parameters == "":
            return -1
        return len(parameters)
    
    @staticmethod
    def __extract_qty_tld_url(domain):
        try:
            
            top_level_domain = domain.split(".")[-1]
            
            return len(top_level_domain)

        except Exception as e:
            return 1
    
    @staticmethod
    def __extract_qty_plus_params(parameters):
        if parameters == "":
            return -1
        
        return parameters.count("+")
    
    @staticmethod
    def __extract_qty_equal_params(parameters):
        if parameters == "":
            return -1
        
        return parameters.count("=")
    
    @staticmethod
    def __extract_qty_dot_params(parameters):
        if parameters == "":    
            return -1
        
        return parameters.count(".")
    
    
    @staticmethod
    def __extract_qty_percent_params(parameters):
        if parameters == "":
            return -1
        return parameters.count("%")
    
    @staticmethod
    def __extract_qty_underline_params(parameters):
        if parameters == "":
            return -1
        return parameters.count("_")
    
    def __generate_dataframe_from_url(self, url:str):
        
        domain = FeatureExtractor.__extract_domain(url)
        directory = FeatureExtractor.__extract_directory(url)
        file = FeatureExtractor.__extract_file(url)
        parameters = FeatureExtractor.__extract_parameters(url)
        
        
        directory_length = FeatureExtractor.__extract_directory_length(directory)
        time_domain_activation = FeatureExtractor.__extract_time_domain_activation(url)
        length_url = FeatureExtractor.__extract_length_url(url)
        file_length = FeatureExtractor.__extract_file_length(file)
        qty_slash_url = FeatureExtractor.__extract_qty_slash_url(url)
        qty_plus_directory = FeatureExtractor.__extract_qty_plus_directory(directory)
        
        domain_length = len(domain)
        qty_vowels_domain = FeatureExtractor.__extract_qty_vowels_domain(domain)
        qty_asterisk_directory = FeatureExtractor.__extract_qty_asterik_directory(directory)
        qty_hyphen_directory = FeatureExtractor.__extract_qty_hyphen_directory(directory)
        
        qty_dot_domain = domain.count(".")
        qty_underline_directory = FeatureExtractor.__extract_qty_underline_directory(directory)
        qty_percent_directory = FeatureExtractor.__extract_qty_percent_directory(directory)
        
        qty_dot_url = url.count(".")
        qty_hyphen_url = url.count("-")
        qty_hyphen_file = FeatureExtractor.__extract_qty_hyphen_file(file)
        
        
        qty_hyphen_domain = domain.count("-")
        qty_params_length = FeatureExtractor.__extract_params_length(parameters)
        
        qty_underline_url = url.count("_")
        qty_tld_url = FeatureExtractor.__extract_qty_tld_url(domain)
        
        qty_plus_params = FeatureExtractor.__extract_qty_plus_params(parameters)
        
        
        qty_percent_url = url.count("%")
        
        
        qty_equal_params = FeatureExtractor.__extract_qty_equal_params(parameters)
        qty_dot_params = FeatureExtractor.__extract_qty_dot_params(parameters)
        
        qty_percent_params = FeatureExtractor.__extract_qty_percent_params(parameters)
        qty_underline_params = FeatureExtractor.__extract_qty_underline_params(parameters)
        
        df_row_array = np.array([directory_length, time_domain_activation, length_url,
                  file_length, qty_slash_url, qty_plus_directory, 
                  domain_length, qty_vowels_domain, qty_asterisk_directory,qty_hyphen_directory,
                  qty_dot_domain, qty_underline_directory, qty_percent_directory,
                  qty_dot_url, qty_hyphen_url, qty_hyphen_file, qty_hyphen_domain, qty_params_length,
                  qty_underline_url,qty_tld_url, qty_plus_params,qty_percent_url,qty_equal_params, 
                  qty_dot_params, qty_percent_params, qty_underline_params])
        
        
        
        df_row = pd.DataFrame(df_row_array.reshape(1,-1), columns = self.columns)
        
        # print(df_row_array)
        return df_row
        
    
    def generate_dataframe_from_urls(self, url_list:List[str]):
        df = pd.DataFrame(columns=self.columns)
        for url in url_list:
            df_row = self.__generate_dataframe_from_url(url)
            df = pd.concat([df, df_row])
        return df

In [270]:
https_url = "https://tinyurl.com/3e5smywh"

In [271]:
fe = FeatureExtractor(features)

In [272]:
temp = fe.generate_dataframe_from_urls([https_url,"https://bloqueioltau.site/Sublime_Sublime_1084356737/Risos_Mae_560734658/#&token=1810416138","https://www.geeksforgeeks.com/","https://ip-72-182-82-263.ip.gw-designs.de/index2.php"])

Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


In [273]:
temp

directory_length time_domain_activation length_url file_length  \
0                8                     -1         28          -1   
0               26                     -1         91          19   
0               -1                   4864         30          -1   
0               10                     -1         52          -1   

  qty_slash_url qty_plus_directory domain_length qty_vowels_domain  \
0             3                  0            11                 3   
0             5                  0            17                 9   
0             3                  0            21                 6   
0             3                  0            33                 5   

  qty_asterisk_directory qty_hyphen_directory  ... qty_hyphen_domain  \
0                      0                    0  ...                 0   
0                      0                    0  ...                 0   
0                     -1                   -1  ...                 0   
0                      0                    0  ...                 5   

  params_length qty_underline_url qty_tld_url qty_plus_params qty_percent_url  \
0            -1                 0           3              -1               0   
0            18                 4           4               0               0   
0            -1                 0           3              -1               0   
0            -1                 0           2              -1               0   

  qty_equal_params qty_dot_params qty_percent_params qty_underline_params  
0               -1             -1                 -1                   -1  
0                1              0                  0                    0  
0               -1             -1                 -1                   -1  
0               -1             -1                 -1                   -1  

[4 rows x 26 columns]

In [274]:
model_path = "saved_models\\20220922011709\\model.joblib"

In [275]:
import joblib

In [276]:
from phishing_domain_detection.component.model_trainer import PhishingEstimator

In [277]:
model = joblib.load(model_path)

FileNotFoundError: [Errno 2] No such file or directory: 'saved_models\\20220922011709\\model.joblib'

In [ ]:
model

RandomForestClassifier()

In [ ]:
np.where(model.predict_proba(temp)[:,1]>model.custom_threshold,1,0)

array([1, 1, 0, 1])

In [ ]:
model.predict(temp)

array([1, 1, 0, 1])

In [ ]:
model.custom_threshold

0.3

In [ ]:
model.predict_proba(temp)

array([[0.15175758, 0.84824242],
       [0.0215    , 0.9785    ],
       [0.89595238, 0.10404762],
       [0.14488528, 0.85511472]])

# Testing feature extractor class

In [ ]:
from phishing_domain_detection.entity.feature_extractor import FeatureExtractor

In [ ]:
fe = FeatureExtractor()

In [ ]:
urls = [https_url,"https://bloqueioltau.site/Sublime_Sublime_1084356737/Risos_Mae_560734658/#&token=1810416138","https://www.geeksforgeeks.com/","https://ip-72-182-82-263.ip.gw-designs.de/index2.php"]

In [ ]:
temp = fe.generate_dataframe_from_urls(urls)

Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


In [ ]:
temp

directory_length time_domain_activation length_url file_length  \
0                8                     -1         28          -1   
0               26                     -1         91          19   
0               -1                   4861         30          -1   
0               10                     -1         52          -1   

  qty_slash_url qty_plus_directory domain_length qty_vowels_domain  \
0             3                  0            11                 3   
0             5                  0            17                 9   
0             3                  0            21                 6   
0             3                  0            33                 5   

  qty_asterisk_directory qty_hyphen_directory  ... qty_hyphen_domain  \
0                      0                    0  ...                 0   
0                      0                    0  ...                 0   
0                     -1                   -1  ...                 0   
0                      0                    0  ...                 5   

  params_length qty_underline_url qty_tld_url qty_plus_params qty_percent_url  \
0            -1                 0           3              -1               0   
0            18                 4           4               0               0   
0            -1                 0           3              -1               0   
0            -1                 0           2              -1               0   

  qty_equal_params qty_dot_params qty_percent_params qty_underline_params  
0               -1             -1                 -1                   -1  
0                1              0                  0                    0  
0               -1             -1                 -1                   -1  
0               -1             -1                 -1                   -1  

[4 rows x 26 columns]

In [ ]:
model.predict(temp)

array([1, 1, 0, 1])