In [1]:
import os

In [2]:
os.chdir('..')

In [3]:
from phishing_domain_detection.entity.model_factory import *

In [4]:
# get_sample_model_config_yaml_file(export_dir="temp//")

In [5]:
mf = ModelFactory('config//model.yaml')

In [6]:
model_schema = mf.read_params('config//model.yaml')

In [7]:
model_schema

{'grid_search': {'class': 'GridSearchCV',
  'module': 'sklearn.model_selection',
  'params': {'cv': 3, 'verbose': 10}},
 'model_selection': {'module_0': {'class': 'LogisticRegression',
   'module': 'sklearn.linear_model',
   'params': {'fit_intecept': False},
   'search_param_grid': {'fit_intercept': [True, False]}},
  'module_1': {'class': 'RandomForestClassifier',
   'module': 'sklearn.ensemble',
   'params': {'n_estimators': 100},
   'search_param_grid': {'n_estimators': [10, 100, 200]}}}}

In [8]:
model_schema.keys()

dict_keys(['grid_search', 'model_selection'])

# Loading class with importlib

In [9]:
import importlib

In [10]:
linear_model = importlib.import_module('sklearn.linear_model')

In [11]:
from sklearn.linear_model import LinearRegression

In [12]:
model = getattr(linear_model,'LinearRegression')

In [13]:
model

sklearn.linear_model._base.LinearRegression

## Setting individual attributes of model objects after loading the model

In [14]:
model_obj = model()

In [15]:
model_obj

LinearRegression()

In [16]:
setattr(model_obj,"fit_intercept",False)

In [17]:
LinearRegression?

Init signature:
LinearRegression(
    *,
    fit_intercept=True,
    normalize='deprecated',
    copy_X=True,
    n_jobs=None,
    positive=False,
)
Docstring:     
Ordinary least squares Linear Regression.

LinearRegression fits a linear model with coefficients w = (w1, ..., wp)
to minimize the residual sum of squares between the observed targets in
the dataset, and the targets predicted by the linear approximation.

Parameters
----------
fit_intercept : bool, default=True
    Whether to calculate the intercept for this model. If set
    to False, no intercept will be used in calculations
    (i.e. data is expected to be centered).

normalize : bool, default=False
    This parameter is ignored when ``fit_intercept`` is set to False.
    If True, the regressors X will be normalized before regression by
    subtracting the mean and dividing by the l2-norm.
    If you wish to standardize, please use
    :class:`~sklearn.preprocessing.StandardScaler` before calling ``fit``
    on an estim

In [18]:
model_obj

LinearRegression(fit_intercept=False)

In [19]:
property_data = {"fit_intercept":False,"n_jobs":-1}

In [20]:
type(property_data)

dict

In [21]:
model_obj = mf.update_property_of_class(instance_ref=model_obj, property_data=property_data)

In [22]:
model_obj

LinearRegression(fit_intercept=False, n_jobs=-1)

# Initializing different models

In [23]:
from sklearn.model_selection import GridSearchCV

In [24]:
from sklearn.linear_model import LogisticRegression

In [25]:
lr = LogisticRegression()

In [26]:
params = {}

In [27]:
x = np.arange(10)

In [28]:
x = x.reshape(-1,1)

In [29]:
y = [0,0,0,0,0,1,1,1,1,1]

In [30]:
grid = GridSearchCV(lr, param_grid=params)

In [31]:
grid.fit(x,y)

GridSearchCV(estimator=LogisticRegression(), param_grid={})

In [32]:
grid.best_estimator_

LogisticRegression()

In [33]:
grid.predict(x)

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [34]:
models = mf.get_initialized_model_list()

In [35]:
models

[InitializedModelDetail(model_serial_number='module_0', model=LogisticRegression(), model_name='sklearn.linear_model.LogisticRegression', param_grid_search={'fit_intercept': [True, False]}),
 InitializedModelDetail(model_serial_number='module_1', model=RandomForestClassifier(), model_name='sklearn.ensemble.RandomForestClassifier', param_grid_search={'n_estimators': [10, 100, 200]})]

In [36]:
from sklearn.ensemble import RandomForestClassifier

In [37]:
RandomForestClassifier?

Init signature:
RandomForestClassifier(
    n_estimators=100,
    *,
    criterion='gini',
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    min_weight_fraction_leaf=0.0,
    max_features='auto',
    max_leaf_nodes=None,
    min_impurity_decrease=0.0,
    bootstrap=True,
    oob_score=False,
    n_jobs=None,
    random_state=None,
    verbose=0,
    warm_start=False,
    class_weight=None,
    ccp_alpha=0.0,
    max_samples=None,
)
Docstring:     
A random forest classifier.

A random forest is a meta estimator that fits a number of decision tree
classifiers on various sub-samples of the dataset and uses averaging to
improve the predictive accuracy and control over-fitting.
The sub-sample size is controlled with the `max_samples` parameter if
`bootstrap=True` (default), otherwise the whole dataset is used to build
each tree.

Read more in the :ref:`User Guide <forest>`.

Parameters
----------
n_estimators : int, default=100
    The number of trees in the forest.


In [38]:
models[0]

InitializedModelDetail(model_serial_number='module_0', model=LogisticRegression(), model_name='sklearn.linear_model.LogisticRegression', param_grid_search={'fit_intercept': [True, False]})

In [39]:
param = models[0].param_grid_search

In [40]:
model = models[0].model

In [41]:
model

LogisticRegression()

In [42]:
grid = GridSearchCV(model,param_grid=param)

In [43]:
grid.fit(x,y)

GridSearchCV(estimator=LogisticRegression(),
             param_grid={'fit_intercept': [True, False]})

In [44]:
grid.best_estimator_

LogisticRegression()

In [45]:
grid.predict([[100]])

array([1])

In [46]:
GridSearchCV?

Init signature:
GridSearchCV(
    estimator,
    param_grid,
    *,
    scoring=None,
    n_jobs=None,
    refit=True,
    cv=None,
    verbose=0,
    pre_dispatch='2*n_jobs',
    error_score=nan,
    return_train_score=False,
)
Docstring:     
Exhaustive search over specified parameter values for an estimator.

Important members are fit, predict.

GridSearchCV implements a "fit" and a "score" method.
It also implements "score_samples", "predict", "predict_proba",
"decision_function", "transform" and "inverse_transform" if they are
implemented in the estimator used.

The parameters of the estimator used to apply these methods are optimized
by cross-validated grid-search over a parameter grid.

Read more in the :ref:`User Guide <grid_search>`.

Parameters
----------
estimator : estimator object
    This is assumed to implement the scikit-learn estimator interface.
    Either estimator needs to provide a ``score`` function,
    or ``scoring`` must be passed.

param_grid : dict or list of

# Grid Search CV operation function

In [47]:
model = models[1]

In [48]:
model

InitializedModelDetail(model_serial_number='module_1', model=RandomForestClassifier(), model_name='sklearn.ensemble.RandomForestClassifier', param_grid_search={'n_estimators': [10, 100, 200]})

In [49]:
x,y

(array([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]]),
 [0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [50]:
mf.execute_grid_search_operation(model,x,y, "f1")

GridSearchBestModel(model_serial_number='module_1', model=RandomForestClassifier(), best_model=RandomForestClassifier(n_estimators=10), best_paramters={'n_estimators': 10}, best_score=0.8)

# Let's check scoring without grid search as well

params:
      n_estimators: 100
    search_param_grid:
      n_estimators:
      - 50
      - 100
      - 200

# Grid Search CV on the initialized model list

In [51]:
models

[InitializedModelDetail(model_serial_number='module_0', model=LogisticRegression(), model_name='sklearn.linear_model.LogisticRegression', param_grid_search={'fit_intercept': [True, False]}),
 InitializedModelDetail(model_serial_number='module_1', model=RandomForestClassifier(), model_name='sklearn.ensemble.RandomForestClassifier', param_grid_search={'n_estimators': [10, 100, 200]})]

In [52]:
mf.initialize_best_paramter_search_for_initialized_models(initialized_model_list=models, input_feature=x, output_feature=y, scoring_parameter="recall")

[GridSearchBestModel(model_serial_number='module_0', model=LogisticRegression(), best_model=LogisticRegression(), best_paramters={'fit_intercept': True}, best_score=1.0),
 GridSearchBestModel(model_serial_number='module_1', model=RandomForestClassifier(), best_model=RandomForestClassifier(n_estimators=10), best_paramters={'n_estimators': 10}, best_score=0.8)]

# Best Model Function

In [53]:
mf.get_best_model?

Signature:
mf.get_best_model(
    X,
    y,
    scoring_parameter_for_grid_search_cv: str,
    base_recall=0.9,
) -> phishing_domain_detection.entity.model_factory.BestModel
Docstring:
Main function of Model Factory script. Simply run this for getting the best model

Args:
    X (_type_): Independant Features
    y (_type_): Dependant Feature
    scoring_parameter_for_grid_search_cv (str): Scoring paramater for Grid Search
    base_recall (float, optional): Minimum desired recall. Defaults to 0.9.

Raises:
    Phishing_Exception: Custom Exception

Returns:
    BestModel: The best model with its parameters
File:      c:\users\rachi\desktop\inueuron\personal projects\phishing-domain-detection-using-machine-learning\phishing_domain_detection\entity\model_factory.py
Type:      method


In [54]:
mf.get_best_model(x,y,"recall")

GridSearchBestModel(model_serial_number='module_0', model=LogisticRegression(), best_model=LogisticRegression(), best_paramters={'fit_intercept': True}, best_score=1.0)

# Building Get Classification Report Function

In [55]:
str(models[0])

"InitializedModelDetail(model_serial_number='module_0', model=LogisticRegression(), model_name='sklearn.linear_model.LogisticRegression', param_grid_search={'fit_intercept': [True, False]})"

In [56]:
best_models = mf.grid_searched_best_model_list

In [57]:
best_models = [model.best_model for model in best_models]

In [58]:
str(best_models[1])

'RandomForestClassifier(n_estimators=10)'

In [59]:
type(best_models[1]).__name__

'RandomForestClassifier'

### Testing Precision and Recall functions

In [60]:
import numpy as np

In [61]:
X = np.arange(10)

In [62]:
X = X.reshape(-1,1)

In [63]:
y = [0,0,0,0,0,1,1,1,1,1]

In [64]:
log_model = best_models[1]

In [65]:
log_model.fit(X,y)

RandomForestClassifier(n_estimators=10)

In [66]:
preds = log_model.predict(X)

In [67]:
from sklearn.metrics import precision_score, recall_score, f1_score

In [68]:
precision_score(y, preds)

1.0

In [69]:
recall_score(y, preds)

1.0

In [70]:
f1_score(y,preds)

1.0

#### Checking get classification report function

In [71]:
X_train = X 
y_train = y

In [72]:
grid_search_models = mf.grid_searched_best_model_list

In [73]:
X_test = np.arange(10,15)

In [74]:
X_test = X_test.reshape(-1,1)

In [79]:
y_test = [1,1,1,1,1]

In [80]:
model_list = [model.best_model for model in grid_search_models ]

In [81]:
model_list

[LogisticRegression(), RandomForestClassifier(n_estimators=10)]

In [82]:
evaluate_classification_report(model_list, 0.5, X_train, y_train, X_test,y_test, 0,0)

1.0 1.0 1.0 1.0
MetricInfoArtifact(model_name='LogisticRegression()', model_object=LogisticRegression(), train_recall=1.0, test_recall=1.0, train_precision=1.0, test_precision=1.0, model_f1=2.0, index_number=0)
1.0 1.0 1.0 1.0
MetricInfoArtifact(model_name='RandomForestClassifier(n_estimators=10)', model_object=RandomForestClassifier(n_estimators=10), train_recall=1.0, test_recall=1.0, train_precision=1.0, test_precision=1.0, model_f1=2.0, index_number=1)


MetricInfoArtifact(model_name='RandomForestClassifier(n_estimators=10)', model_object=RandomForestClassifier(n_estimators=10), train_recall=1.0, test_recall=1.0, train_precision=1.0, test_precision=1.0, model_f1=2.0, index_number=1)